services:
  # MARIADB
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: inception_mariadb
    restart: always
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb_volumn:/opt/mariadb/data

  # NGINX
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: inception_nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - mariadb

networks:
  inception_network:
    external: true

volumes:
  mariadb_volumn: